In [1]:
import numpy as np


In [3]:
ridership=np.array([ 
    [   0,    0,    2,    5,    0],
    [1478, 3877, 3674, 2328, 2539],
    [1613, 4088, 3991, 6461, 2691],
    [1560, 3392, 3826, 4787, 2613],
    [1608, 4802, 3932, 4477, 2705],
    [1576, 3933, 3909, 4979, 2685],
    [  95,  229,  255,  496,  201],
    [   2,    0,    1,   27,    0],
    [1438, 3785, 3589, 4174, 2215],
    [1342, 4043, 4009, 4665, 3033]
                    ])

In [4]:
ridership[2,3]

6461

In [5]:
ridership[2,]

array([1613, 4088, 3991, 6461, 2691])

In [8]:
#slicing of 2-d array
#coloumn slicing
ridership[0:2,]

array([[   0,    0,    2,    5,    0],
       [1478, 3877, 3674, 2328, 2539]])

In [9]:
ridership[0:2,2:3]

array([[   2],
       [3674]])

In [10]:
ridership[0:2,2]

array([   2, 3674])

In [11]:
ridership[0:,2:4]

array([[   2,    5],
       [3674, 2328],
       [3991, 6461],
       [3826, 4787],
       [3932, 4477],
       [3909, 4979],
       [ 255,  496],
       [   1,   27],
       [3589, 4174],
       [4009, 4665]])

In [13]:
a = np.array([
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ])

In [16]:
print a.mean()
print a.mean(axis=0)
print a.mean(axis=1)

5.0
[ 4.  5.  6.]
[ 2.  5.  8.]


In [18]:
print a.mean(axis=0)[0]

4.0
