In [1]:
import numpy as np


In [2]:
countries=np.array(['Afghanistan', 'Albania', 'Algeria', 'Angola', 'Argentina',
    'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas',
    'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium',
    'Belize', 'Benin', 'Bhutan', 'Bolivia',
    'Bosnia and Herzegovina'])

employment=np.array([ 55.70000076,  51.40000153,  50.5       ,  75.69999695,
    58.40000153,  40.09999847,  61.5       ,  57.09999847,
    60.90000153,  66.59999847,  60.40000153,  68.09999847,
    66.90000153,  53.40000153,  48.59999847,  56.79999924,
    71.59999847,  58.40000153,  70.40000153,  41.20000076])

In [5]:
print countries[4]
print employment[4]

Argentina
58.40000153


In [7]:
countries[1:4]

array(['Albania', 'Algeria', 'Angola'], 
      dtype='|S22')

In [8]:
for country in countries:
    print country

Afghanistan
Albania
Algeria
Angola
Argentina
Armenia
Australia
Austria
Azerbaijan
Bahamas
Bahrain
Bangladesh
Barbados
Belarus
Belgium
Belize
Benin
Bhutan
Bolivia
Bosnia and Herzegovina


In [12]:
# functions like max ,min,mean,standard deviation
print np.mean(employment)
print np.std(employment)
print np.min(employment)
print np.max(employment)

58.6850000385
9.33826911369
40.09999847
75.69999695


In [17]:
# maximum values of employment and countries

def max_value(countries,employment):
    max_employment=np.max(employment)
    index=-1
    for rate in employment:
        index=index+1
        if rate==max_employment:
            break;
    max_country=countries[index]
    return (max_country,max_employment)
    
print max_value(countries,employment)    

('Angola', 75.699996949999999)


In [19]:
# numpy argmax function return the index of maximum value and argmin vice-versa
i=np.argmax(employment)
print employment[i]
print countries[i]

j=np.argmin(employment)
print employment[j]
print countries[j]

75.69999695
Angola
40.09999847
Armenia


In [25]:
# vectorized addition

a=[1,2,3]
b=[4,5,6]
print np.add(a,b) #numpy addition
print a+b         #python addition
print a*3         #python multiplication

[5 7 9]
[1, 2, 3, 4, 5, 6]
[1, 2, 3, 1, 2, 3, 1, 2, 3]


In [33]:
# vectorized operations

a=np.array([1, 2, 3, 4])
b=np.array([1, 2, 1, 2])
print a+b
print a-b
print a*b
print a**2
print b/a

[2 4 4 6]
[0 0 2 2]
[1 4 3 8]
[ 1  4  9 16]
[1 1 0 0]


In [34]:
a = np.array([1, 2, 3, 4])
b = 2
print a + b
print a - b
print a * b
print a / b
print a ** b
    
   

[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0 1 1 2]
[ 1  4  9 16]


In [36]:
a=np.array([True,True,False,False])
b=np.array([True,False,True,False])

print a & b
print a | b
print ~a
print a & True
print a & False
print a | True
print a | False

[ True False False False]
[ True  True  True False]
[False False  True  True]
[ True  True False False]
[False False False False]
[ True  True  True  True]
[ True  True False False]


In [37]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 4, 3, 2, 1])
    
print a > b
print a >= b
print a < b
print a <= b
print a == b
print a != b

[False False False  True  True]
[False False  True  True  True]
[ True  True False False False]
[ True  True  True False False]
[False False  True False False]
[ True  True False  True  True]


In [38]:
a = np.array([1, 2, 3, 4])
b = 2
    
print a > b
print a >= b
print a < b
print a <= b
print a == b
print a != b

[False False  True  True]
[False  True  True  True]
[ True False False False]
[ True  True False False]
[False  True False False]
[ True False  True  True]


In [40]:
a = np.array([1, 2, 3, 4])
b = np.array([True, True, False, False])
    
print a[b]
print a[np.array([True, False, True, False])]

[1 2]
[1 3]


In [41]:
a=np.array([1,2,3,4,5])
a[a==2]

array([2])

In [43]:
def mean_time_for_paid_students(time_spent, days_to_cancel):
    '''
    Fill in this function to calculate the mean time spent in the classroom
    for students who stayed enrolled at least (greater than or equal to) 7 days.
    Unlike in Lesson 1, you can assume that days_to_cancel will contain only
    integers (there are no students who have not canceled yet).
    
    The arguments are NumPy arrays. time_spent contains the amount of time spent
    in the classroom for each student, and days_to_cancel contains the number
    of days until each student cancel. The data is given in the same order
    in both arrays.
    '''
    time_spent_below7=time_spent[days_to_cancel>7]
    
    return np.mean(time_spent_below7)

# Time spent in the classroom in the first week for 20 students
time_spent = np.array([
       12.89697233,    0.        ,   64.55043217,    0.        ,
       24.2315615 ,   39.991625  ,    0.        ,    0.        ,
      147.20683783,    0.        ,    0.        ,    0.        ,
       45.18261617,  157.60454283,  133.2434615 ,   52.85000767,
        0.        ,   54.9204785 ,   26.78142417,    0.
])

# Days to cancel for 20 students
days_to_cancel = np.array([
      4,   5,  37,   3,  12,   4,  35,  38,   5,  37,   3,   3,  68,
     38,  98,   2, 249,   2, 127,  35
])

print mean_time_for_paid_students(time_spent, days_to_cancel)

41.0540034855


In [45]:
a=np.array([1,2,3,4])
b=a
a=a+np.array([1,1,1,1])
print b

[1 2 3 4]


In [51]:
a=np.array([1,2,3,4])
mean1=np.mean(a)
b=a[a>mean1]
print b


[3 4]
