In [1]:
import pandas as pd
import numpy as np

In [2]:
enrollment_df=pd.DataFrame({
        'account_key':[448,448,448,448,448],
        'status':['canceled','canceled','canceled','canceled','current'],
        'join_date':['2014-11-10','2014-11-5','2015-01-27','2015-08-27','2015-04-06'],
        'days_to_cancel':[65,5,0,0,np.nan],
        'is_udacity':[True,True,True,True,True]    
    })

enrollment_df

account_key  days_to_cancel is_udacity   join_date    status
0          448            65.0       True  2014-11-10  canceled
1          448             5.0       True   2014-11-5  canceled
2          448             0.0       True  2015-01-27  canceled
3          448             0.0       True  2015-08-27  canceled
4          448             NaN       True  2015-04-06   current

In [3]:
enrollment_df.mean()

account_key       448.0
days_to_cancel     17.5
is_udacity          1.0
dtype: float64

In [4]:
enrollment_df.describe()

C:\Users\goutham1996\Anaconda2\lib\site-packages\numpy\lib\function_base.py:3834: RuntimeWarning: Invalid value encountered in percentile
  RuntimeWarning)


account_key  days_to_cancel
count          5.0        4.000000
mean         448.0       17.500000
std            0.0       31.754265
min          448.0        0.000000
25%          448.0             NaN
50%          448.0             NaN
75%          448.0             NaN
max          448.0       65.000000

In [5]:
ridership_df=pd.DataFrame( 
    data=[[   0,    0,    2,    5,    0],
          [1478, 3877, 3674, 2328, 2539],
          [1613, 4088, 3991, 6461, 2691],
          [1560, 3392, 3826, 4787, 2613],
          [1608, 4802, 3932, 4477, 2705],
          [1576, 3933, 3909, 4979, 2685],
          [  95,  229,  255,  496,  201],
          [   2,    0,    1,   27,    0],
          [1438, 3785, 3589, 4174, 2215],
          [1342, 4043, 4009, 4665, 3033]],
    index=['05-01-11', '05-02-11', '05-03-11', '05-04-11', '05-05-11',
           '05-06-11', '05-07-11', '05-08-11', '05-09-11', '05-10-11'],
    columns=['R003', 'R004', 'R005', 'R006', 'R007']
        
    )

ridership_df

R003  R004  R005  R006  R007
05-01-11     0     0     2     5     0
05-02-11  1478  3877  3674  2328  2539
05-03-11  1613  4088  3991  6461  2691
05-04-11  1560  3392  3826  4787  2613
05-05-11  1608  4802  3932  4477  2705
05-06-11  1576  3933  3909  4979  2685
05-07-11    95   229   255   496   201
05-08-11     2     0     1    27     0
05-09-11  1438  3785  3589  4174  2215
05-10-11  1342  4043  4009  4665  3033

In [6]:
# accessing elements by index

ridership_df.loc['05-02-11']

R003    1478
R004    3877
R005    3674
R006    2328
R007    2539
Name: 05-02-11, dtype: int64

In [7]:
# accessing elements by position

ridership_df.iloc[9]

R003    1342
R004    4043
R005    4009
R006    4665
R007    3033
Name: 05-10-11, dtype: int64

In [8]:
ridership_df['R003']

05-01-11       0
05-02-11    1478
05-03-11    1613
05-04-11    1560
05-05-11    1608
05-06-11    1576
05-07-11      95
05-08-11       2
05-09-11    1438
05-10-11    1342
Name: R003, dtype: int64

In [9]:
ridership_df.iloc[1,3]

2328

In [10]:
ridership_df.values

array([[   0,    0,    2,    5,    0],
       [1478, 3877, 3674, 2328, 2539],
       [1613, 4088, 3991, 6461, 2691],
       [1560, 3392, 3826, 4787, 2613],
       [1608, 4802, 3932, 4477, 2705],
       [1576, 3933, 3909, 4979, 2685],
       [  95,  229,  255,  496,  201],
       [   2,    0,    1,   27,    0],
       [1438, 3785, 3589, 4174, 2215],
       [1342, 4043, 4009, 4665, 3033]], dtype=int64)

In [11]:
ridership_df.values.mean()

2342.5999999999999

In [12]:
ridership_df.mean(axis=0)

R003    1071.2
R004    2814.9
R005    2718.8
R006    3239.9
R007    1868.2
dtype: float64

In [13]:
ridership_df.mean(axis=1)

05-01-11       1.4
05-02-11    2779.2
05-03-11    3768.8
05-04-11    3235.6
05-05-11    3504.8
05-06-11    3416.4
05-07-11     255.2
05-08-11       6.0
05-09-11    3040.2
05-10-11    3418.4
dtype: float64

In [14]:
ridership_df.loc['05-10-11'].values

array([1342, 4043, 4009, 4665, 3033], dtype=int64)

In [15]:
ridership_df.loc['05-10-11'].values.argmax()

3

In [16]:
ridership_df.iloc[0].values.argmax()

3

In [17]:
ridership_df.iloc[0].argmax()

'R006'

In [18]:
subway_df=pd.read_csv('nyc_subway_weather.csv')
subway_df.head()

UNIT     DATEn     TIMEn  ENTRIESn   EXITSn  ENTRIESn_hourly  \
0  R003  05-01-11  00:00:00   4388333  2911002              0.0   
1  R003  05-01-11  04:00:00   4388333  2911002              0.0   
2  R003  05-01-11  12:00:00   4388333  2911002              0.0   
3  R003  05-01-11  16:00:00   4388333  2911002              0.0   
4  R003  05-01-11  20:00:00   4388333  2911002              0.0   

   EXITSn_hourly             datetime  hour  day_week     ...       pressurei  \
0            0.0  2011-05-01 00:00:00     0         6     ...           30.22   
1            0.0  2011-05-01 04:00:00     4         6     ...           30.25   
2            0.0  2011-05-01 12:00:00    12         6     ...           30.28   
3            0.0  2011-05-01 16:00:00    16         6     ...           30.26   
4            0.0  2011-05-01 20:00:00    20         6     ...           30.28   

  rain  tempi  wspdi meanprecipi  meanpressurei  meantempi  meanwspdi  \
0    0   55.9    3.5         0.0         30.258      55.98       7.86   
1    0   52.0    3.5         0.0         30.258      55.98       7.86   
2    0   62.1    6.9         0.0         30.258      55.98       7.86   
3    0   57.9   15.0         0.0         30.258      55.98       7.86   
4    0   52.0   10.4         0.0         30.258      55.98       7.86   

   weather_lat  weather_lon  
0    40.700348   -73.887177  
1    40.700348   -73.887177  
2    40.700348   -73.887177  
3    40.700348   -73.887177  
4    40.700348   -73.887177  

[5 rows x 27 columns]

In [19]:
subway_df.head().describe()

ENTRIESn     EXITSn  ENTRIESn_hourly  EXITSn_hourly       hour  \
count        5.0        5.0              5.0            5.0   5.000000   
mean   4388333.0  2911002.0              0.0            0.0  10.400000   
std          0.0        0.0              0.0            0.0   8.294577   
min    4388333.0  2911002.0              0.0            0.0   0.000000   
25%    4388333.0  2911002.0              0.0            0.0   4.000000   
50%    4388333.0  2911002.0              0.0            0.0  12.000000   
75%    4388333.0  2911002.0              0.0            0.0  16.000000   
max    4388333.0  2911002.0              0.0            0.0  20.000000   

       day_week  weekday   latitude  longitude  fog     ...       pressurei  \
count       5.0      5.0   5.000000   5.000000  5.0     ...          5.0000   
mean        6.0      0.0  40.689945 -73.872564  0.0     ...         30.2580   
std         0.0      0.0   0.000000   0.000000  0.0     ...          0.0249   
min         6.0      0.0  40.689945 -73.872564  0.0     ...         30.2200   
25%         6.0      0.0  40.689945 -73.872564  0.0     ...         30.2500   
50%         6.0      0.0  40.689945 -73.872564  0.0     ...         30.2600   
75%         6.0      0.0  40.689945 -73.872564  0.0     ...         30.2800   
max         6.0      0.0  40.689945 -73.872564  0.0     ...         30.2800   

       rain      tempi      wspdi  meanprecipi  meanpressurei  meantempi  \
count   5.0   5.000000   5.000000          5.0   5.000000e+00       5.00   
mean    0.0  55.980000   7.860000          0.0   3.025800e+01      55.98   
std     0.0   4.266966   4.908462          0.0   3.972055e-15       0.00   
min     0.0  52.000000   3.500000          0.0   3.025800e+01      55.98   
25%     0.0  52.000000   3.500000          0.0   3.025800e+01      55.98   
50%     0.0  55.900000   6.900000          0.0   3.025800e+01      55.98   
75%     0.0  57.900000  10.400000          0.0   3.025800e+01      55.98   
max     0.0  62.100000  15.000000          0.0   3.025800e+01      55.98   

          meanwspdi  weather_lat  weather_lon  
count  5.000000e+00     5.000000     5.000000  
mean   7.860000e+00    40.700348   -73.887177  
std    9.930137e-16     0.000000     0.000000  
min    7.860000e+00    40.700348   -73.887177  
25%    7.860000e+00    40.700348   -73.887177  
50%    7.860000e+00    40.700348   -73.887177  
75%    7.860000e+00    40.700348   -73.887177  
max    7.860000e+00    40.700348   -73.887177  

[8 rows x 21 columns]

In [21]:
df1=pd.DataFrame({'a':[1,2,3],'b':[4,5,6]})
df1

a  b
0  1  4
1  2  5
2  3  6

In [22]:
df2=pd.DataFrame({'a':[2,3,4],'b':[1,3,5]})
df2

a  b
0  2  1
1  3  3
2  4  5

In [23]:
df1+df2

a   b
0  3   5
1  5   8
2  7  11

In [24]:
df3=pd.DataFrame({'c':[2,3,4],'d':[1,3,5]})
df3

c  d
0  2  1
1  3  3
2  4  5

In [25]:
df1+df3

a   b   c   d
0 NaN NaN NaN NaN
1 NaN NaN NaN NaN
2 NaN NaN NaN NaN

In [26]:
df1 = pd.DataFrame({'a': [1, 2, 3], 'b': [4, 5, 6], 'c': [7, 8, 9]},
                       index=['row1', 'row2', 'row3'])
df2 = pd.DataFrame({'a': [10, 20, 30], 'b': [40, 50, 60], 'c': [70, 80, 90]},
                       index=['row4', 'row3', 'row2'])
print df1
print df2
print df1+df2

      a  b  c
row1  1  4  7
row2  2  5  8
row3  3  6  9
       a   b   c
row4  10  40  70
row3  20  50  80
row2  30  60  90
         a     b     c
row1   NaN   NaN   NaN
row2  32.0  65.0  98.0
row3  23.0  56.0  89.0
row4   NaN   NaN   NaN


In [37]:
entries_and_exits = pd.DataFrame({
    'ENTRIESn': [3144312, 3144335, 3144353, 3144424, 3144594,
                 3144808, 3144895, 3144905, 3144941, 3145094],
    'EXITSn': [1088151, 1088159, 1088177, 1088231, 1088275,
               1088317, 1088328, 1088331, 1088420, 1088753]})
entries_and_exits

ENTRIESn   EXITSn
0   3144312  1088151
1   3144335  1088159
2   3144353  1088177
3   3144424  1088231
4   3144594  1088275
5   3144808  1088317
6   3144895  1088328
7   3144905  1088331
8   3144941  1088420
9   3145094  1088753

In [39]:
entries_and_exits['ENTRIESn'].values

array([3144312, 3144335, 3144353, 3144424, 3144594, 3144808, 3144895,
       3144905, 3144941, 3145094], dtype=int64)

In [53]:
k=entries_and_exits.shift(periods=1,axis=0).fillna(0).astype(int)
k


ENTRIESn   EXITSn
0         0        0
1   3144312  1088151
2   3144335  1088159
3   3144353  1088177
4   3144424  1088231
5   3144594  1088275
6   3144808  1088317
7   3144895  1088328
8   3144905  1088331
9   3144941  1088420

In [54]:
entries_and_exits-k

ENTRIESn   EXITSn
0   3144312  1088151
1        23        8
2        18       18
3        71       54
4       170       44
5       214       42
6        87       11
7        10        3
8        36       89
9       153      333

In [55]:
entries_and_exits = pd.DataFrame(
    {'ENTRIESn': [10, 40, 60, 65, 85], 'EXITSn': [0, 10, 20, 60, 60]},
    index=[0, 1, 2, 3, 4]
)

In [58]:
def get_hourly_entries_and_exits(entries_and_exits):
    '''
    Fill in this function to take a DataFrame with cumulative entries
    and exits (entries in the first column, exits in the second) and
    return a DataFrame with hourly entries and exits (entries in the
    first column, exits in the second).
    '''
    k= entries_and_exits.shift(1)
    return entries_and_exits-k
    
print get_hourly_entries_and_exits(entries_and_exits)    

   ENTRIESn  EXITSn
0       NaN     NaN
1      30.0    10.0
2      20.0    10.0
3       5.0    40.0
4      20.0     0.0


In [59]:
df=pd.DataFrame({'a':[1,2,3],'b':[4,5,6],'c':[7,8,9]})
df

a  b  c
0  1  4  7
1  2  5  8
2  3  6  9

In [62]:
# apply this function to each and every element
def cleanstate(x):
    return x+1

In [63]:
df.applymap(cleanstate)

a  b   c
0  2  5   8
1  3  6   9
2  4  7  10

In [65]:
grades_df = pd.DataFrame(
    data={'exam1': [43, 81, 78, 75, 89, 70, 91, 65, 98, 87],
          'exam2': [24, 63, 56, 56, 67, 51, 79, 46, 72, 60]},
    index=['Andre', 'Barry', 'Chris', 'Dan', 'Emilio', 
           'Fred', 'Greta', 'Humbert', 'Ivan', 'James']
)
grades_df

exam1  exam2
Andre       43     24
Barry       81     63
Chris       78     56
Dan         75     56
Emilio      89     67
Fred        70     51
Greta       91     79
Humbert     65     46
Ivan        98     72
James       87     60

In [66]:
def cleanmarks(x):
    if x>=90:
        return 'A'
    elif x>=80:
        return 'B'
    elif x>=70:
        return 'C'
    elif x>=60:
        return 'D'
    else:
        return 'F'

In [67]:
grades_df.applymap(cleanmarks)

exam1 exam2
Andre       F     F
Barry       B     D
Chris       C     F
Dan         C     F
Emilio      B     D
Fred        C     F
Greta       A     C
Humbert     D     F
Ivan        A     C
James       B     D

In [68]:
s=pd.Series([1,2,3,4])
df=pd.DataFrame({
        0: [10, 20, 30, 40],
        1: [50, 60, 70, 80],
        2: [90, 100, 110, 120],
        3: [130, 140, 150, 160]})

In [69]:
print s
print df

0    1
1    2
2    3
3    4
dtype: int64
    0   1    2    3
0  10  50   90  130
1  20  60  100  140
2  30  70  110  150
3  40  80  120  160


In [70]:
print df+s

    0   1    2    3
0  11  52   93  134
1  21  62  103  144
2  31  72  113  154
3  41  82  123  164


In [71]:
print s+df

    0   1    2    3
0  11  52   93  134
1  21  62  103  144
2  31  72  113  154
3  41  82  123  164


In [72]:
df=pd.DataFrame({0: [10], 1: [20], 2: [30], 3: [40]})

In [73]:
print df

    0   1   2   3
0  10  20  30  40


In [74]:
print s+df

    0   1   2   3
0  11  22  33  44


In [75]:
df = pd.DataFrame({0: [10, 20, 30, 40]})

In [76]:
print df
print s+df

    0
0  10
1  20
2  30
3  40
    0   1   2   3
0  11 NaN NaN NaN
1  21 NaN NaN NaN
2  31 NaN NaN NaN
3  41 NaN NaN NaN


In [77]:
s = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])
print s

a    1
b    2
c    3
d    4
dtype: int64


In [78]:
df = pd.DataFrame({
        'a': [10, 20, 30, 40],
        'b': [50, 60, 70, 80],
        'c': [90, 100, 110, 120],
        'd': [130, 140, 150, 160]
    })

In [79]:
print df

    a   b    c    d
0  10  50   90  130
1  20  60  100  140
2  30  70  110  150
3  40  80  120  160


In [80]:
print s+df

    a   b    c    d
0  11  52   93  134
1  21  62  103  144
2  31  72  113  154
3  41  82  123  164


In [81]:
s = pd.Series([1, 2, 3, 4])
df = pd.DataFrame({
        'a': [10, 20, 30, 40],
        'b': [50, 60, 70, 80],
        'c': [90, 100, 110, 120],
        'd': [130, 140, 150, 160]
    })
print s
print df

0    1
1    2
2    3
3    4
dtype: int64
    a   b    c    d
0  10  50   90  130
1  20  60  100  140
2  30  70  110  150
3  40  80  120  160


In [82]:
print s+df

    0   1   2   3   a   b   c   d
0 NaN NaN NaN NaN NaN NaN NaN NaN
1 NaN NaN NaN NaN NaN NaN NaN NaN
2 NaN NaN NaN NaN NaN NaN NaN NaN
3 NaN NaN NaN NaN NaN NaN NaN NaN
